version: "3.9"

services:

  backend-clinic-management:
    container_name: backend-clinic-management
    build:
      context: .
      dockerfile: Dockerfile  # Tên Dockerfile trong thư mục hiện tại
    image: haphuthinh/backend-clinic-management:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 600M
