version: "3.9"

services:

  backend-clinic-management:
    container_name: backend-clinic-management
    image: haphuthinh/backend-clinic-management
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7068:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 600M
